AWSTemplateFormatVersion: 2010-09-09
Description: OneNineAI G2 - Task 4 on DevOps and Automation (PostgreSQL DB)

Parameters:

  DBName:
    Description: The database name for Aurora PostgreSQL DB instance
    Type: String
    Default: "OneNineAIG2T4DB"

  DBMasterUsername:
    Description: The database master/super username
    Type: String
    Default: "onenineai"

  DBMasterUserPassword:
    Description: The password for database master/super user
    Type: String
    NoEcho: "true"
    Default: "onenineai"

  DBInstanceClass:
    Description: Database instance class
    Type: String
    Default: "db.t3.micro"

  DBClusterInstanceClass:
    Description: Database instance class
    Type: String
    Default: "db.t3.micro"

  AllocatedStorage:
    Description: The memory to be allocated for your database
    Type: Number
    Default: "20"

  EnablePerformanceInsights:
    Description: A value that indicates whether to enable Performance Insights for the DB instance.
    Type: String
    Default: false

Resources:
  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      Tags:
        - Key: "Name"
          Value: mypostgresdb3
      DBInstanceIdentifier: mypostgresdb3
      DBName:
        Ref: DBName
      AllocatedStorage:
        Ref: AllocatedStorage
      DBInstanceClass:
        Ref: DBInstanceClass
      Engine: postgres
      EngineVersion: 15.4
      MasterUsername:
        Ref: DBMasterUsername
      MasterUserPassword:
        Ref: DBMasterUserPassword
      StorageType: gp2
      StorageEncrypted: "true"
      EnablePerformanceInsights:
        Ref: EnablePerformanceInsights
      AutoMinorVersionUpgrade: true
      CopyTagsToSnapshot: true
      BackupRetentionPeriod: 7
      PubliclyAccessible: false

Outputs:
  RDSEndpoint:
    Description: RDS Database Endpoint
    Value:
      Fn::GetAtt:
        - DBInstance
        - Endpoint.Address
    Export:
      Name:
        Fn::Sub: "RDSEndpoint2"