AWSTemplateFormatVersion: 2010-09-09
Description: OneNineAI G2 - Task 4 on DevOps and Automation (S3 Bucket)

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: s3-capstone-onenine
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Name
          Value: MyS3Bucket
  
