name: CI-OneNine-DevOps

on:
  push:
    branches:
      - main

jobs:
  steps:
    - name: Establish AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
        aws-region: "us-east-2"

    - name: Create EC2 instance running RHEL
      uses: aws cloudformation deploy --template-file ec2.yaml --stack-name ec2-onenine

    - name: Create RDS using PostgreSQL
      uses: aws cloudformation deploy --template-file db.yaml --stack-name postgre-onenine

    - name: Start S3 Bucket
      uses: aws cloudformation deploy --template-file s3.yaml --stack-name s3-onenine

    - name: Script to clone Git repo of Chatbot UI into specified folder
      uses: install.sh